GET http://localhost:9091/api/task/users
Content-Type: application/json

###

POST http://localhost:9091/api/task/users
Content-Type: application/json

{
  "userUUID": "test-uuid",
  "userId": "testId",
  "userNickName": "testNickName",
  "userEmail": "testEmail"
}

###

DELETE http://localhost:9091/api/task/users/test-uuid

###

PUT http://localhost:9091/api/task/users/test-uuid
Content-Type: application/json

{
  "userUUID": "test",
  "userId": "update testId",
  "userNickName": "update testNickName",
  "userEmail": "update testEmail"
}

###

GET http://localhost:9091/api/task/users/test-uuid

###

GET http://localhost:9091/api/task/projects/4

###

POST http://localhost:9091/api/task/projects
Content-Type: application/json

{
  "projectName": "testProjectName",
  "projectDescription": "testProjectDescription",
  "projectStatus": "INACTIVE",
  "userUUID": "test-uuid"
}

###

PUT http://localhost:9091/api/task/projects/12
Content-Type: application/json

{
  "projectName": "update testProjectName",
  "projectDescription": "update testProjectDescription",
  "projectStatus": "ACTIVE"
}

###

DELETE http://localhost:9091/api/task/projects/12

###
#project-users

POST http://localhost:9091/api/task/projects/4/users/fc51ea9c-637a-4374-b007-df8592daeb5c

###

GET http://localhost:9091/api/task/projects/4/users

###

GET http://localhost:9091/api/task/users/fc51ea9c-637a-4374-b007-df8592daeb5c/projects

###

DELETE http://localhost:9091/api/task/projects/4/users/fc51ea9c-637a-4374-b007-df8592daeb5c

###

DELETE http://localhost:9091/api/task/projects/4

###

#Tasks

POST http://localhost:9091/api/task/tasks
Content-Type: application/json

{
    "taskName": "testTaskName",
    "taskContent": "testTaskContent",
    "taskCreationDate": "2020-01-01T00:00:00",
    "taskEndDate": "2020-01-01T00:00:00",
    "userUUID": "fc51ea9c-637a-4374-b007-df8592daeb5c",
    "projectId": 5
}

###

GET http://localhost:9091/api/task/tasks/12

###

GET http://localhost:9091/api/task/tasks/projects/5

###

GET http://localhost:9091/api/task/tasks/users/fc51ea9c-637a-4374-b007-df8592daeb5c/admin

###

PUT http://localhost:9091/api/task/tasks/12
Content-Type: application/json

{
  "taskName": "update testTaskName",
  "taskContent": "update testTaskContent",
  "taskCreationDate": "2020-01-01T00:00:00",
  "taskEndDate": "2020-01-01T00:00:00"
}

###

DELETE http://localhost:9091/api/task/tasks/13

###

#milestone

POST http://localhost:9091/api/task/milestones
Content-Type: application/json

{
  "milestoneName": "testMilestoneName",
  "milestoneStartDate": "2020-01-01T00:00:00",
  "milestoneEndDate": "2020-01-01T00:00:00",
  "milestoneStatus": "INACTIVE",
  "projectId": 5
}

###

PUT http://localhost:9091/api/task/milestones/3
Content-Type: application/json

{
  "milestoneName": "update testMilestoneName",
  "milestoneStartDate": "2020-01-01T00:00:00",
  "milestoneEndDate": "2020-01-01T00:00:00",
  "milestoneStatus": "ACTIVE"
}

###

DELETE http://localhost:9091/api/task/milestones/3

###

GET http://localhost:9091/api/task/milestones/3

###

GET http://localhost:9091/api/task/milestones/projects/5

###

#Milestones-Tasks

POST http://localhost:9091/api/task/milestones/4/tasks/12

###

GET http://localhost:9091/api/task/tasks/12/milestones
###


GET http://localhost:9091/api/task/milestones/3/tasks

###

DELETE http://localhost:9091/api/task/milestones/4/tasks/12

###
#tag

POST http://localhost:9091/api/task/tags
Content-Type: application/json

{
  "tagName": "testTagName",
  "projectId": 5
}

###
PUT http://localhost:9091/api/task/tags/2
Content-Type: application/json

{
  "tagName": "update testTagName"
}

###
GET http://localhost:9091/api/task/tags/1

###

GET http://localhost:9091/api/task/tags/projects/5

###

DELETE http://localhost:9091/api/task/tags/2

###

#tag-tasks
POST http://localhost:9091/api/task/tasks/12/tags/1

###
GET http://localhost:9091/api/task/tasks/12/tags

###
GET http://localhost:9091/api/task/tags/1/tasks

###
DELETE http://localhost:9091/api/task/tasks/12/tags/1

###
#private Long commentId;
#private String commentContent;
#private String commentCreationDate;
#private String userUUID;
#private Long taskId;
#comment
POST http://localhost:9091/api/task/comments
Content-Type: application/json

{
  "commentContent": "testCommentContent",
  "commentCreationDate": "2020-01-01T00:00:00",
  "userUUID": "fc51ea9c-637a-4374-b007-df8592daeb5c",
  "taskId": 12
}

###

GET http://localhost:9091/api/task/comments/1

###

GET http://localhost:9091/api/task/comments/tasks/12

###

PUT http://localhost:9091/api/task/comments/1
Content-Type: application/json

{
  "commentContent": "update testCommentContent",
  "commentCreationDate": "2020-01-01T00:00:00",
  "userUUID": "fc51ea9c-637a-4374-b007-df8592daeb5c",
  "taskId": 12
}

###

DELETE http://localhost:9091/api/task/comments/1

###
#UserTask

POST http://localhost:9091/api/task/tasks/12/users/fc51ea9c-637a-4374-b007-df8592daeb5c

###

GET http://localhost:9091/api/task/users/fc51ea9c-637a-4374-b007-df8592daeb5c/tasks

###

GET http://localhost:9091/api/task/tasks/12/users

###

DELETE http://localhost:9091/api/task/tasks/12/users/fc51ea9c-637a-4374-b007-df8592daeb5c
